spring:
  config:
    activate:
      on-profile: test
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:dashboard_test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password: ""
      driver-class-name: org.h2.Driver
      pool-name: HikariPool
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        '[show_sql]': true
        '[format_sql]': true
        '[use_sql_comments]': true
        '[generate_statistics]': true