spring:
  config:
    activate:
      on-profile: dev
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:dashboard;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password: ""
      driver-class-name: org.h2.Driver
      pool-name: HikariPool
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        '[show_sql]': true
        '[format_sql]': true
        '[use_sql_comments]': true
        '[generate_statistics]': true

  # 데이터베이스 초기화 설정
  sql:
    init:
      mode: always
      data-locations: classpath:db/data-dev.sql
  h2:
    console:
      enabled: true
      path: /h2-console
